spring:
  config:
    activate:
      on-profile: qa
build:
  version: "2.0"

cards:
  message: "Welcome to EasyBank cards related qa APIs "
  contactDetails:
    name: "Dimba oay - QA Lead"
    email: "dimba@easybank.com"
  onCallSupport:
    - (333) 343-1234
    - (333) 098-1345