spring:
  config:
    activate:
      on-profile: prod
build:
  version: "1.0"

cards:
  message: "Welcome to EasyBank cards related prod APIs "
  contactDetails:
    name: "Vamshi - Product Owner"
    email: "vamshi@easybank.com"
  onCallSupport:
    - (111) 555-1234
    - (111) 523-1345